### ISSUE TITLE
[1.10.2][Forge 2075]Crash On Server Load

### ISSUE THREAD

**Issue by Hastling** [zsawyer/MumbleLink#12]
http://pastebin.com/XZAFGgER

**Comment by zsawyer** [comment]
In case someone else has the same issue, here is an explanation...

When this mod is installed on a Minecraft server this error message will be thrown: 

`Caused by: java.lang.RuntimeException: Attempted to load class zsawyer/mods/mumblelink/MumbleLinkImpl for invalid side SERVER`

It is because this mod is client-side only. I chose to let the game crash because there is no reason to install it on a server, there would only be draw-backs ranging from possible performance loss, all the way to mod-compatibility issues.
