### ISSUE TITLE
Minecraft 1.16.1 / Forge 32 support

### ISSUE THREAD

**Issue by devurandom** [zsawyer/MumbleLink#31]
It would be nice to have some (preview) support for Minecraft 1.16.1 using [Forge 32](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.16.1.html).

**Comment by zsawyer** [comment]
I did try compiling with the following versions but got an error. 
```
ext.modversion = "4.5.0"
ext.mcversion = "1.16.1"
ext.forgeversion = "32.0.108"
```
```
    mappings channel: 'snapshot', version: "20200514-1.16"
```

The build is successful and the mod is loaded. 
Then comes this error message:

> [07Feb2021 03:52:38.133] [Thread-10/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getInstance()Lnet/minecraft/client/Minecraft;

This error message suggests that there is an incompatibility between the mapping and the actual forge build version. 
I cannot resolve it - its an issue with the forge preview because there is no stable version.

Also it is extremely hard to find another mapping that I could try because MCP is being out-phased and mappings supposedly are created manually now since version 1.6.

**Comment by zsawyer** [comment]
Using Discord I have received feedback that this error is due to not reobfuscating the jar. 

Solution was to run "reobfJar" instead of just "jar" build command.
