### ISSUE TITLE
I am not able to use proximity chat on Ubuntu with Badlion 3 (1.8.9)

### ISSUE THREAD

**Issue by devanshgohil07** [zsawyer/MumbleLink#54]
So I followed all the steps correctly and proximity chat is still not working for me. I am using the latest stable version of mumble installed using sudo apt install command.

[latest.log](https://github.com/zsawyer/MumbleLink/files/7271419/latest.log)

https://pastebin.ubuntu.com/p/PBV8jbqZKt/

**Comment by zsawyer** [comment]
Sorry for the late reply. You probably have figured it out already. Your installation is full of errors.
Infact it even seems to miss a crucial dependency or have wrong mod versions for your minecraft version. 
It seems your MC is 1.8 but you are using 1.17.1 mods or something else so that not even forge is working for you. 
You first need to fix your installation and base mods. 

[17:01:21] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.FMLCommonHandler
